baseURL = "https://tenzzzzzz.github.io/"
languageCode = "en-us"
title = "Pitou"

[params]
  author = "Yosef Khaled"
  authorTitle = "Security Researcher | Hacker | Developer"
  description = "Personal blog about cybersecurity and tech"


[params.social]
  linkedin = "https://www.linkedin.com/in/yourusername"
  x = "https://x.com/yourusername"
  discord = "https://discord.com/users/YOUR_ID"
  
[outputs]
  home = ["HTML", "RSS", "JSON"]
[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = false
  [markup.goldmark.renderer]
    unsafe = true
  
[caches]
  [caches.images]
    dir = ':cacheDir/images'